### ISSUE TITLE
🪲[Bug]: Parameter set not supported

### ISSUE THREAD

**Issue by ssg47** [PSModule/PSSemVer#14]
### Describe the bug

The examples say this should work:

    $Version = New-PSSemVer -Version 1.0.0 -PreRelease 'alpha' -Build '2020-01-01'

but it errors on parameter set.

### Version information

1.0.11

### To reproduce

Run the line shown below

### Code snippet

```powershell
New-PSSemVer -Version 1.0.0 -PreRelease 'alpha' -Build '2020-01-01'
```

### Relevant output

```Shell
WindowsPowerShell 5.1.19041.4522 gives:

New-PSSemVer : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:5
+     New-PSSemVer -Version 1.0.0 -PreRelease 'alpha' -Build '2020-01-0 ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-PSSemVer], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,New-PSSemVer


PowerShell 7.4.3 gives

New-PSSemVer: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

**Comment by ssg47** [comment]
I wanted to create a fix and a PR but I couldn't work out how to build it locally in order to test it.

**Comment by MariusStorhaug** [comment]
Hi @ssg47. Thank you for the report. The parameter set usage that you have doesnt necessarily work yet, but it makes sense to support it. The currently supported way would be:

```pwsh
New-PSSemVer -Version '1.0.0-alpha+2020-01-01'

# OR

New-PSSemVer -Major 1 -Minor 0 -Patch 0 -PreRelease 'alpha' -Build '2020-01-01'
```

But combining the two would be ok i guess. Just a issue with what would win if we had the following code:

```pwsh
New-PSSemVer -Version '1.0.0-alpha' -PreRelease 'beta' -Build '2020-01-01'
```

Thoughts?

**Comment by MariusStorhaug** [comment]
I havnt really added a good way to build the module locally, will add that to the framework so i can create that for all the modules in the module library. Think what would work is to fork the repo, create the test covering what you want it to support and make sure that the test is met by adding the changes to the functions. With this you get regression testing too ;)

**Comment by ssg47** [comment]
> But combining the two would be ok i guess. Just a issue with what would win if we had the following code:
> 
> ```powershell
> New-PSSemVer -Version '1.0.0-alpha' -PreRelease 'beta' -Build '2020-01-01'
> ```
> 
> Thoughts?

My own approach would be to generate an error here since the user has definitely made a mistake.

**Comment by ssg47** [comment]
What is the point of the `$Path` variable  in `PSSemVer.Tests.ps1`?

I had to add a line to that file to get the tests to work but I've removed it from the pushed files.

    Describe 'PSSemVer' {
        
        Import-Module $Path -Force
    
        Describe 'Function: New-PSSemVer' {

**Comment by ssg47** [comment]
I've forked the repo and submitted a fix here: https://github.com/ssg47/PSSemVer/tree/issue14.

**Comment by MariusStorhaug** [comment]
Closing as stale.

**Comment by MariusStorhaug** [comment]
Sorry for taking so long to complete this. But here we are.
