### ISSUE TITLE
🪲[Bug]: '2024.08.06' => `The version string is not a valid SemVer string`

### ISSUE THREAD

**Issue by o-l-a-v** [PSModule/PSSemVer#19]
### Describe the bug

```pwsh
PS > New-PSSemVer -Version '2024.08.06'

OperationStopped: The version string is not a valid SemVer string

PS >
```

To my knowledge `2024.08.06` is a valid semantic version.

### Version information

* PowerShell v7.4.4 x64
* PSSemVer v1.0.13

### To reproduce

See description.

### Code snippet

See description.

### Relevant output

See description.

**Comment by o-l-a-v** [comment]
semver.org regexes does not return `2024.08.06` as valid, strange.

* <https://regex101.com/r/Ly7O1x/3/>
* <https://regex101.com/r/vkijKf/1/>

**Comment by MariusStorhaug** [comment]
Leading nulls seem to be the issue

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by o-l-a-v** [comment]
Aah, because of leading zeros.

* `2024.08.06` => Invalid
* `2024.8.6` => Valid

---

Edit: You beat me to it. 😋

**Comment by o-l-a-v** [comment]
Aah, because of leading zeros.

* `2024.08.06` => Invalid
* `2024.8.6` => Valid

---

Edit: You beat me to it. 😋
