### ISSUE TITLE
🚀[Feature]: Make it Windows PowerShell 5.1 compatible

### ISSUE THREAD

**Issue by o-l-a-v** [PSModule/PSSemVer#3]
### Description

Windows PowerShell does not have `[semver]` like PowerShell Core and would greatly benefit from having this module. And the changes needed to make PSSemVer 5.1 compatible is very small, in my limited testing.

The class line 112-114 ( <https://github.com/PSModule/PSSemVer/blob/5df47a9e98180205e6e22660aea451d5baa7b718/src/PSSemVer/classes/PSSemVer.ps1#L112-L114> ) must change to:

```powershell
$this.Major = $(if($version.Major -lt 0){0}else{$version.Major})
$this.Minor = $(if($version.Minor -lt 0){0}else{$version.Minor})
$this.Patch = $(if($version.Build -lt 0){0}else{$version.Build})
```

or

```powershell
$this.Major = if ($version.Major -lt 0) {0} else {$version.Major}
$this.Minor = if ($version.Minor -lt 0) {0} else {$version.Minor}
$this.Patch = if ($version.Build -lt 0) {0} else {$version.Build}
```

And the filter `ConvertTo-PSSemVer` line 35 ( <https://github.com/PSModule/PSSemVer/blob/5df47a9e98180205e6e22660aea451d5baa7b718/src/PSSemVer/public/ConvertTo-PSSemVer.ps1#L35> ) must change to:

```powershell
if ([string]::IsNullOrEmpty($Version)) {
```

**Comment by MariusStorhaug** [comment]
@o-l-a-v: Thanks for the feedback, been working on the testing framework after I saw this. Making sure I can test and dynamically add the correct info to the manifest based on what works and not. Will also add some compatibility checks to the testing suite so I can detect issues. Now I am at the point where I need to fix this. :)

Again, thank you!
