### ISSUE TITLE
🪲[Bug]: Invalid version numbers like `1.0.0-beta..1` and `1.0.0-beta!1` should error but doesn't

### ISSUE THREAD

**Issue by o-l-a-v** [PSModule/PSSemVer#7]
### Describe the bug

Invalid version numbers like `1.0.0-beta..1` and `1.0.0-beta!1` should error but doesn't.

Semver.org has suggested regex expressions for valid version numbers:

* <https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string>

Mentioned invalid version numbers does not pass the semver.org linked regex101 tests:

* <https://regex101.com/r/Ly7O1x/3/>
* <https://regex101.com/r/vkijKf/1/>

### Version information

Module v1.0.5

### To reproduce

See **Code snippet**.

### Code snippet

```powershell
### Should work
[PSSemVer]'1'
[PSSemVer]'1.0'
[PSSemVer]'1.0.0-beta1'
[PSSemVer]'1.0.0-beta.1'

### Should error
[PSSemVer]'1.0.0-beta..1'
[PSSemVer]'1.0.0-beta.!.1'
[PSSemVer]'1.0.0-beta!1'
```

### Relevant output

```Shell
PS > [PSSemVer]'1.0.0-beta.!.1'

Prefix        : 
Major         : 1
Minor         : 0
Patch         : 0
Prerelease    : beta.!.1
BuildMetadata : 

PS >
```

**Comment by MariusStorhaug** [comment]
@o-l-a-v : That is the regex it is using. Adding some tests to validate.

**Comment by MariusStorhaug** [comment]
Ye, the bug is in the coercion i added. Makes sense i guess to remove that to make it truly compatible.
I do have a "loose" pattern, where it allows a prefix. will remove the coercion and test again.
